name: Run Automated Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Run Web UI Tests
        run: ./gradlew testWeb --info

      - name: Run API Tests
        run: ./gradlew testApi --info

      - name: Debug - Cek struktur direktori
        run: ls -R build/reports || true

      - name: Upload Web UI Test Report
        uses: actions/upload-artifact@v4
        with:
          name: web-ui-test-report
          path: build/reports/web-ui/cucumber.html
          if-no-files-found: warn

      - name: Upload API Test Report
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: build/reports/api/cucumber.html
          if-no-files-found: warn
